version: '3'

services:

  app-dvwa:
    ports:
      - "${PORTS_DVWA:-8000}:80"

  app-juiceshop:
    ports:
      - "${PORTS_JUICESHOP:-8001}:3000"
      
  app-nowasp:
    ports:
      - "${PORTS_NOWASP:-8002}:80"

  app-securityninjas:
    ports:
      - "${PORTS_SECURITYNINJAS:-8003}:80"

  app-webgoat:
    ports:
      - "${PORTS_WEBGOAT:-8004}:8080"

  app-xvwa:
    ports:
      - "${PORTS_XVWA:-8005}:80"
