version: '3'

services:

  app-dvwa:
    networks:
      - default
      - nginx-proxy

  app-juiceshop:
    networks:
      - default
      - nginx-proxy

  app-nowasp:
    networks:
      - default
      - nginx-proxy

  app-securityninjas:
    networks:
      - default
      - nginx-proxy

  app-webgoat:
    networks:
      - default
      - nginx-proxy

  app-xvwa:
    networks:
      - default
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
