version: '3'

services:

  app-dvwa:
    environment:
      VIRTUAL_HOST: dvwa.${NGINX_PROXY_HOSTNAME}
    networks:
      - default
      - nginx-proxy

  app-juiceshop:
    environment:
      VIRTUAL_HOST: juiceshop.${NGINX_PROXY_HOSTNAME}
      VIRTUAL_PORT: 3000
    networks:
      - default
      - nginx-proxy

  app-nowasp:
    environment:
      VIRTUAL_HOST: nowasp.${NGINX_PROXY_HOSTNAME}
    networks:
      - default
      - nginx-proxy

  app-securityninjas:
    environment:
      VIRTUAL_HOST: securityninjas.${NGINX_PROXY_HOSTNAME}
    networks:
      - default
      - nginx-proxy

  app-webgoat:
    environment:
      VIRTUAL_HOST: webgoat.${NGINX_PROXY_HOSTNAME}
      VIRTUAL_PORT: 8080
    networks:
      - default
      - nginx-proxy

  app-xvwa:
    environment:
      VIRTUAL_HOST: xvwa.${NGINX_PROXY_HOSTNAME}
    networks:
      - default
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: ${NGINX_PROXY_NETWORK_NAME:-nginx-proxy}
